services:
  database:
    image: postgres
    container_name: gourmand-database
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - dokploy-network

  migration:
    build:
      context: .
      target: migration
    env_file:
      - .env
    restart: "no"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - dokploy-network

  app:
    container_name: gourmand-app
    build:
      context: .
      target: runner
    env_file:
      - .env
    working_dir: /app
    restart: unless-stopped
    depends_on:
      migration:
        condition: service_completed_successfully
    volumes:
      - gourmand_data:${NUXT_IPX_FS_DIR}

  adminer:
    image: adminer
    container_name: gourmand-adminer
    restart: unless-stopped

volumes:
  gourmand_data:
